# Generated by Django 5.2.7 on 2025-10-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stromverbrauch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(db_index=True, unique=True, verbose_name='Datum')),
                ('verbrauch_kwh', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Verbrauch (kWh)')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stromverbrauch',
                'verbose_name_plural': 'Stromverbräuche',
                'db_table': 'fact_stromverbrauch',
                'ordering': ['-datum'],
                'indexes': [models.Index(fields=['-datum'], name='idx_strom_datum')],
                'constraints': [models.CheckConstraint(condition=models.Q(('verbrauch_kwh__gte', 0)), name='chk_verbrauch_positiv')],
            },
        ),
    ]
