# Generated by Django 5.2.7 on 2025-10-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billa', '0003_copy_name_normalisiert_to_korrigiert'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billaprodukt',
            index=models.Index(fields=['name_korrigiert'], name='billa_produ_name_ko_293315_idx'),
        ),
    ]
