# Generated by Django 5.2.7 on 2025-10-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billa', '0004_add_name_korrigiert'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillaKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ueberkategorie', models.CharField(max_length=200)),
                ('produktgruppe', models.CharField(blank=True, max_length=200, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ueberkategorie', 'produktgruppe'],
                'unique_together': {('ueberkategorie', 'produktgruppe')},
            },
        ),
    ]
