# Generated by Django 5.2.7 on 2025-10-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billa', '0009_migrate_kategorie_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billaprodukt',
            options={'ordering': ['-anzahl_kaeufe']},
        ),
        migrations.RemoveIndex(
            model_name='billaprodukt',
            name='billa_produ_name_no_58b515_idx',
        ),
        migrations.RemoveIndex(
            model_name='billaprodukt',
            name='billa_produ_ueberka_a4e129_idx',
        ),
        migrations.RemoveIndex(
            model_name='billaprodukt',
            name='billa_produ_name_ko_293315_idx',
        ),
        migrations.RemoveField(
            model_name='billaprodukt',
            name='letzte_aktualisierung',
        ),
        migrations.AlterField(
            model_name='billaprodukt',
            name='anzahl_kaeufe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billaprodukt',
            name='durchschnittspreis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billaprodukt',
            name='letzter_preis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billaprodukt',
            name='marke',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billaprodukt',
            name='name_korrigiert',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='billaprodukt',
            name='name_normalisiert',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='billaprodukt',
            name='name_original',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='billaprodukt',
            name='produktgruppe_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billaprodukt',
            name='ueberkategorie_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='billaprodukt',
            table=None,
        ),
    ]
