# Generated by Django 5.2.7 on 2025-10-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billa', '0010_alter_billaprodukt_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillaKategorie',
        ),
        migrations.RemoveField(
            model_name='billaprodukt',
            name='produktgruppe_alt',
        ),
        migrations.RemoveField(
            model_name='billaprodukt',
            name='ueberkategorie_alt',
        ),
    ]
