# Generated by Django 5.2.7 on 2025-10-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'dim_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimAccountTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounttypes', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'dim_accounttypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimAssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
                ('display_name', models.CharField(blank=True, max_length=500, null=True)),
                ('category_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_asset_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCalender',
            fields=[
                ('datum', models.DateField(primary_key=True, serialize=False)),
                ('jahr', models.IntegerField()),
                ('wochentag', models.CharField(max_length=500)),
                ('kalenderwoche', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_calender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'dim_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_group', models.CharField(db_column='category_group', max_length=500)),
            ],
            options={
                'db_table': 'dim_categorygroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'dim_flag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimJahr',
            fields=[
                ('jahr', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_jahr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimMonat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monat', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'dim_monat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPayee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'dim_payee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactAssetsLiabilitiesOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(blank=True, max_length=500, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('date_zone', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'fact_assets_liabilities_overview',
                'ordering': ['category', 'asset_name', '-date_zone'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactBetriebskosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.IntegerField()),
                ('monat', models.IntegerField()),
                ('vs_posten', models.CharField(max_length=500)),
                ('wohnung_betrag_netto', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('wohnung_betrag_brutto', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('tg_betrag_netto', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('tg_betrag_brutto', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('gesamt_betrag_brutto', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'fact_betriebskosten',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactTransactionsRobert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('outflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'fact_transactions_robert',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactTransactionsSigi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('outflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'fact_transactions_sigi',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
    ]
