# Generated by Django 5.2.7 on 2025-10-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_table', models.CharField(choices=[('sigi', 'Sigi'), ('robert', 'Robert')], default='sigi', max_length=10)),
                ('memo', models.TextField(blank=True, null=True)),
                ('outflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('frequency', models.CharField(choices=[('monthly', 'Monatlich'), ('quarterly', 'Vierteljährlich'), ('yearly', 'Jährlich')], default='monthly', max_length=20)),
                ('start_date', models.DateField(help_text='Datum der ersten Transaktion')),
                ('end_date', models.DateField(blank=True, help_text='Optional: Enddatum für wiederkehrende Transaktionen', null=True)),
                ('next_execution_date', models.DateField(help_text='Nächstes Datum für die automatische Erstellung')),
                ('is_active', models.BooleanField(default=True, help_text='Aktive Transaktionen werden automatisch erstellt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='finance.dimaccount')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='finance.dimcategory')),
                ('flag', models.ForeignKey(blank=True, db_column='flag_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.dimflag')),
                ('payee', models.ForeignKey(db_column='payee_id', on_delete=django.db.models.deletion.CASCADE, to='finance.dimpayee')),
            ],
            options={
                'verbose_name': 'Scheduled Transaction',
                'verbose_name_plural': 'Scheduled Transactions',
                'db_table': 'scheduled_transactions',
                'ordering': ['next_execution_date', 'payee'],
            },
        ),
    ]
