# Generated by Django 5.2.7 on 2025-10-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_billakategoriemapping_billaeinkauf_billaprodukt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billaartikel',
            name='preis_pro_einheit',
            field=models.DecimalField(decimal_places=2, help_text='Automatisch berechnet: gesamtpreis / menge', max_digits=10, null=True, verbose_name='Preis pro Einheit'),
        ),
    ]
