# Generated by Django 5.2.7 on 2025-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_registereddevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereddevice',
            name='device_fingerprint',
            field=models.CharField(max_length=255),
        ),
    ]
