# Generated by Django 5.2.7 on 2025-10-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_fix_produkt_duplikate'),
        ('finance', '0005_alter_billaartikel_preis_pro_einheit'),
    ]

    operations = [
    ]
