# Generated by Django 5.2.7 on 2025-10-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_merge_20251014_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='billaprodukt',
            name='produktgruppe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Produktgruppe'),
        ),
        migrations.AlterField(
            model_name='billaprodukt',
            name='name_original',
            field=models.CharField(help_text='Eine der Original-Varianten dieses Produkts', max_length=500, verbose_name='Original-Name'),
        ),
    ]
