# Generated by Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_billaprodukt_produktgruppe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billaprodukt',
            name='ueberkategorie',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Überkategorie',
                help_text='Übergeordnete Kategorie wie Gemüse, Obst, Milchprodukte, etc.'
            ),
        ),
    ]