# Generated by Django 5.2.7 on 2025-10-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_billaprodukt_ueberkategorie'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billaprodukt',
            index=models.Index(fields=['ueberkategorie'], name='billa_produ_ueberka_a4e129_idx'),
        ),
    ]
