# Generated by Django 5.2.7 on 2025-10-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_billaprodukt_billa_produ_ueberka_a4e129_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillaKategorieMapping',
        ),
        migrations.RemoveIndex(
            model_name='billaprodukt',
            name='billa_produ_kategor_471062_idx',
        ),
        migrations.RemoveField(
            model_name='billaprodukt',
            name='kategorie',
        ),
        migrations.AlterField(
            model_name='billaprodukt',
            name='ueberkategorie',
            field=models.CharField(blank=True, db_index=True, help_text='Übergeordnete Kategorie wie Gemüse, Obst, Milchprodukte, etc.', max_length=100, null=True, verbose_name='Überkategorie'),
        ),
    ]
