# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('finance', '0008_billaprodukt_ueberkategorie'),
    ]

    operations = [
        # Index entfernen
        migrations.RemoveIndex(
            model_name='billaprodukt',
            name='billa_produ_kategor_471062_idx',  # Anpassen falls der Name anders ist
        ),

        # Feld entfernen
        migrations.RemoveField(
            model_name='billaprodukt',
            name='kategorie',
        ),

        # Neuen Index für ueberkategorie hinzufügen
        migrations.AddIndex(
            model_name='billaprodukt',
            index=migrations.Index(fields=['ueberkategorie'], name='billa_produ_ueberka_a4e129_idx'),
        ),

        # BillaKategorieMapping kann entfernt werden, falls nicht mehr benötigt
        migrations.DeleteModel(
            name='BillaKategorieMapping',
        ),
    ]