# Generated by Django 5.2.7 on 2025-10-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_remove_billaeinkauf_billa_einka_filiale_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="billaeinkauf",
            name="billa_einka_filiale_idx",
        ),
        migrations.RenameIndex(
            model_name="billaeinkauf",
            new_name="billa_einka_datum_641dea_idx",
            old_name="billa_einka_datum_5f130f_idx",
        ),
    ]
