# Beispiel-Konfigurationen für den Billa Price Crawler
# Diese Datei dient als Vorlage und wird nicht automatisch eingelesen.

# Standardlauf für die Hauptfiliale 1330
standard:
  limit: 75
  filial_nr: "1330"
  delay: 1.8
  min_confidence: 82
  export_csv: data/exports/billa_prices_standard.csv
  log_file: logs/billa_price_standard.log

# Vorsichtiger Testlauf ohne Datenbank-Schreibzugriff
integration_test:
  limit: 10
  dry_run: true
  delay: 2.5
  min_confidence: 75
  exclude_category:
    - "Einweg"
    - "Pfand"

# Filial-spezifischer Lauf für Urlaubsregion (Filiale 2015)
urlaubspreise:
  limit: 40
  filial_nr: "2015"
  delay: 2.0
  include_category:
    - "Getränke"
    - "Milchprodukte"
  export_csv: data/exports/billa_prices_urlaub.csv

# Langsamer Crawl für umfangreiche Vergleiche
vollabgleich:
  limit: 120
  delay: 3.5
  batch_size: 8
  min_confidence: 78
  export_csv: data/exports/billa_prices_full.csv
  log_file: logs/billa_price_full.log
  min_purchases: 2
