# Generated by Django 5.2.7 on 2025-10-20 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitpandaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('total_crypto_value_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fiat_value_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_commodities_value_eur', models.DecimalField(decimal_places=2, default=0, help_text='Gold, Silber, etc.', max_digits=12)),
                ('total_value_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('raw_data', models.JSONField(blank=True, help_text='Raw API Response für Debugging', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitpanda_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitpanda Snapshot',
                'verbose_name_plural': 'Bitpanda Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
