# Generated by Django 5.2.7 on 2025-10-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitpanda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitpandaSnapshot',
        ),
    ]
