# Generated by Django 5.2.7 on 2025-10-20 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitpanda', '0002_delete_bitpandasnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitpandaHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(help_text='Asset Symbol (z.B. BTC, ETH, AAPL)', max_length=50)),
                ('asset_class', models.CharField(help_text='Asset-Klasse', max_length=50)),
                ('balance', models.DecimalField(decimal_places=8, default=0, help_text='Aktueller Bestand', max_digits=20)),
                ('average_buy_price', models.DecimalField(blank=True, decimal_places=8, help_text='Durchschnittlicher Kaufpreis', max_digits=20, null=True)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, help_text='Gesamt investierter Betrag in EUR', max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitpanda_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitpanda Bestand',
                'verbose_name_plural': 'Bitpanda Bestände',
                'ordering': ['-balance'],
                'unique_together': {('user', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='BitpandaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Bitpanda Transaction ID', max_length=100)),
                ('timestamp', models.DateTimeField(help_text='Zeitpunkt der Transaktion')),
                ('transaction_type', models.CharField(choices=[('buy', 'Kauf'), ('sell', 'Verkauf'), ('deposit', 'Einzahlung'), ('withdrawal', 'Auszahlung'), ('transfer', 'Transfer')], max_length=20)),
                ('direction', models.CharField(choices=[('incoming', 'Eingehend'), ('outgoing', 'Ausgehend')], max_length=10)),
                ('amount_fiat', models.DecimalField(blank=True, decimal_places=2, help_text='Betrag in Fiat-Währung', max_digits=20, null=True)),
                ('fiat', models.CharField(default='EUR', help_text='Fiat-Währung (z.B. EUR, USD)', max_length=10)),
                ('amount_asset', models.DecimalField(blank=True, decimal_places=8, help_text='Menge des Assets', max_digits=20, null=True)),
                ('asset', models.CharField(blank=True, help_text='Asset Symbol (z.B. BTC, ETH, AAPL)', max_length=50, null=True)),
                ('asset_market_price', models.DecimalField(blank=True, decimal_places=8, help_text='Marktpreis des Assets', max_digits=20, null=True)),
                ('asset_market_price_currency', models.CharField(blank=True, default='EUR', max_length=10, null=True)),
                ('asset_class', models.CharField(blank=True, choices=[('Cryptocurrency', 'Kryptowährung'), ('Stock (derivative)', 'Aktie'), ('ETF', 'ETF'), ('Metal', 'Edelmetall'), ('Fiat', 'Fiat')], help_text='Asset-Klasse', max_length=50, null=True)),
                ('product_id', models.CharField(blank=True, help_text='Bitpanda Product ID', max_length=50, null=True)),
                ('fee', models.DecimalField(decimal_places=8, default=0, help_text='Transaktionsgebühr', max_digits=20)),
                ('fee_asset', models.CharField(blank=True, help_text='Währung der Gebühr', max_length=10, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=8, help_text='Spread', max_digits=20, null=True)),
                ('spread_currency', models.CharField(blank=True, help_text='Währung des Spreads', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitpanda_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitpanda Transaktion',
                'verbose_name_plural': 'Bitpanda Transaktionen',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='bitpanda_bi_user_id_84b934_idx'), models.Index(fields=['user', 'asset'], name='bitpanda_bi_user_id_4841ee_idx'), models.Index(fields=['transaction_type'], name='bitpanda_bi_transac_b2faad_idx')],
                'unique_together': {('user', 'transaction_id')},
            },
        ),
    ]
