# Generated by Django 5.2.7 on 2025-10-20 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpanda', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bitpandaholding',
            name='isin',
            field=models.CharField(blank=True, help_text='ISIN für Aktien und ETFs', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bitpandatransaction',
            name='isin',
            field=models.CharField(blank=True, help_text='ISIN für Aktien und ETFs (z.B. US0378331005 für Apple)', max_length=12, null=True),
        ),
        migrations.AddIndex(
            model_name='bitpandaholding',
            index=models.Index(fields=['isin'], name='bitpanda_bi_isin_29da03_idx'),
        ),
        migrations.AddIndex(
            model_name='bitpandatransaction',
            index=models.Index(fields=['isin'], name='bitpanda_bi_isin_e06692_idx'),
        ),
    ]
