# Generated by Django 5.2.7 on 2025-10-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitpanda', '0004_bitpandaholding_isin_bitpandatransaction_isin_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bitpandaholding',
            name='bitpanda_bi_isin_29da03_idx',
        ),
        migrations.RemoveIndex(
            model_name='bitpandatransaction',
            name='bitpanda_bi_isin_e06692_idx',
        ),
        migrations.RemoveField(
            model_name='bitpandaholding',
            name='isin',
        ),
        migrations.RemoveField(
            model_name='bitpandatransaction',
            name='isin',
        ),
    ]
