# Generated by Django 5.2.7 on 2025-10-20 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpanda', '0005_remove_bitpandaholding_bitpanda_bi_isin_29da03_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitpandaAssetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Datum der Transaktion')),
                ('payed', models.DecimalField(decimal_places=2, help_text='Bezahlter/Erhaltener Betrag in EUR (positiv bei Kauf, negativ bei Verkauf)', max_digits=20)),
                ('units', models.DecimalField(decimal_places=8, help_text='Anzahl gekaufter/verkaufter Einheiten (positiv bei Kauf, negativ bei Verkauf)', max_digits=20)),
                ('price_per_unit', models.DecimalField(decimal_places=8, help_text='Preis pro Einheit zum Transaktionszeitpunkt', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holding', models.ForeignKey(help_text='Referenz zum Asset', on_delete=django.db.models.deletion.CASCADE, related_name='historical_values', to='bitpanda.bitpandaholding')),
            ],
            options={
                'verbose_name': 'Asset-Transaktion (historisch)',
                'verbose_name_plural': 'Asset-Transaktionen (historisch)',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['holding', 'date'], name='bitpanda_bi_holding_2fa062_idx'), models.Index(fields=['date'], name='bitpanda_bi_date_7cab24_idx')],
            },
        ),
    ]
