# Generated by Django 5.2.7 on 2025-10-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpanda', '0006_bitpandaassetvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitpandaassetvalue',
            name='payed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bezahlter/Erhaltener Betrag in EUR (positiv bei Kauf, negativ bei Verkauf)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='bitpandaassetvalue',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Anzahl gekaufter/verkaufter Einheiten (positiv bei Kauf, negativ bei Verkauf)', max_digits=20, null=True),
        ),
    ]
