# Generated by Django 5.2.7 on 2025-10-20 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpanda', '0007_alter_bitpandaassetvalue_payed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitpandaassetvalue',
            options={'ordering': ['-date'], 'verbose_name': 'Asset-Transaktion', 'verbose_name_plural': 'Asset-Transaktionen'},
        ),
        migrations.AlterModelOptions(
            name='bitpandaholding',
            options={'ordering': ['asset'], 'verbose_name': 'Bitpanda Asset', 'verbose_name_plural': 'Bitpanda Assets'},
        ),
        migrations.RenameField(
            model_name='bitpandaholding',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bitpandaholding',
            name='average_buy_price',
        ),
        migrations.RemoveField(
            model_name='bitpandaholding',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bitpandaholding',
            name='total_invested',
        ),
        migrations.AddField(
            model_name='bitpandaholding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bitpandaassetvalue',
            name='date',
            field=models.DateField(help_text='Datum der Transaktion oder Preisupdate'),
        ),
        migrations.AlterField(
            model_name='bitpandaassetvalue',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=8, help_text='Preis pro Einheit', max_digits=20),
        ),
        migrations.DeleteModel(
            name='BitpandaTransaction',
        ),
    ]
