# Generated by Django 5.2.7 on 2025-10-29 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Pflanzenname')),
                ('species', models.CharField(blank=True, max_length=200, verbose_name='Art/Sorte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pflanze',
                'verbose_name_plural': 'Pflanzen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plants/%Y/%m/')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='Aufnahmedatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plants.plant')),
            ],
            options={
                'verbose_name': 'Pflanzenbild',
                'verbose_name_plural': 'Pflanzenbilder',
                'ordering': ['-captured_at'],
            },
        ),
    ]
