# Generated by Django 5.2.7 on 2025-10-31 09:32

import plants.models
import plants.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_add_plantgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plantgroup',
            name='unique_plantgroup_per_user',
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='captured_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Aufnahmedatum'),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(storage=plants.storage.PlantPhotoStorage(), upload_to=plants.models.plant_image_upload_to),
        ),
        migrations.AlterUniqueTogether(
            name='plantgroup',
            unique_together={('name', 'user')},
        ),
    ]
