# Generated by Django 5.2.7 on 2025-10-31 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_remove_plantgroup_unique_plantgroup_per_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Raum')),
                ('is_outdoor', models.BooleanField(default=False, verbose_name='Außenbereich')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon (Bootstrap-Icon-Key, optional)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pflanzenraum',
                'verbose_name_plural': 'Pflanzenräume',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='plants', to='plants.plantroom', verbose_name='Räume/Standorte'),
        ),
    ]
